image: docker:latest
services:
  - docker:dind

variables:
  DOCKER_TLS_CERTDIR: ""
  IMAGE: "$CI_REGISTRY_IMAGE"

stages:
  - build

before_script:
  - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" "$CI_REGISTRY"

build:
  stage: build
  script:
    - docker build -t "$IMAGE:$CI_COMMIT_SHA" .
    - docker push "$IMAGE:$CI_COMMIT_SHA"
    - docker tag "$IMAGE:$CI_COMMIT_SHA" "$IMAGE:latest"
    - docker push "$IMAGE:latest"
  only:
    - main
    - merge_requests
